# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: runTest.js CI

on: [push]
 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install Dependencies 
      run: npm install
      
    - name: Test with Jasmine
      run: |
       npm install jasmine --save-dev
       npm run test-init
       npm test
